spring.application.name=demo

# Oracle Autonomous Database
spring.datasource.url=jdbc:oracle:thin:@backend3db_tp
spring.datasource.username=BANKXYZ_APP
spring.datasource.password=${BANKXYZ_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Ubicación del Wallet
spring.datasource.hikari.data-source-properties[oracle.net.tns_admin]=${ORACLE_WALLET_DIR}

# Spring Batch
spring.batch.job.enabled=true
spring.batch.job.name=estadosCuentaAnualesJob
spring.batch.jdbc.initialize-schema=never
spring.batch.jdbc.isolation-level-for-create=READ_COMMITTED

app.totalRecords=1000
app.poolSize=3
app.maxSkipCount=100