spring.application.name=bff-web

server.port=8081

bankxyz.backend.url=http://localhost:8080

bff.security.username=${BFF_WEB_USERNAME}
bff.security.password=${BFF_WEB_PASSWORD}

# JWT
bff.jwt.secret=${BFF_WEB_JWT_SECRET}
bff.jwt.issuer=bff-web
bff.jwt.scope=WEB
bff.jwt.expiration-seconds=1800

# SSL
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${BFF_WEB_SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-web