server:
  port: 8083

bankxyz:
  backend:
    url: ${BACKEND_URL:http://localhost:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      circuitBreaker:
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

bff:
  channel: atm

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER_URI:http://localhost:9000}