spring.application.name=bff-mobile

server.port=8082

bankxyz.backend.url=http://localhost:8080

bff.security.username=${BFF_MOBILE_USERNAME}
bff.security.password=${BFF_MOBILE_PASSWORD}

# JWT
bff.jwt.secret=${BFF_MOBILE_JWT_SECRET}
bff.jwt.issuer=bff-mobile
bff.jwt.scope=MOBILE
bff.jwt.expiration-seconds=1800

# SSL
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${BFF_MOBILE_SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-mobile