spring.application.name=bff-atm

server.port=8083

bankxyz.backend.url=http://localhost:8080

bff.security.username=${BFF_ATM_USERNAME}
bff.security.password=${BFF_ATM_PASSWORD}

# JWT
bff.jwt.secret=${BFF_ATM_JWT_SECRET}
bff.jwt.issuer=bff-atm
bff.jwt.scope=ATM
bff.jwt.expiration-seconds=1800

# SSL
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=${BFF_ATM_SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-atm